### ISSUE TITLE
Multiple dockable containers

### ISSUE THREAD

**Issue by luiq54** [gilzoide/godot-dockable-container#9]
Can you add support for multiple containers ? 
This will be useful for creating layouts where some parts are dockable and can be moved around and some parts are static.  Ability to move panels from one container to another will be great!

**Comment by gilzoide** [comment]
I don't know if I get what you want to do exactly. Can you elaborate the idea further? Maybe show a concrete example of where these containers would be and what you want to be moved or not.

I'm saying this because the DockableContainer already have the `rearrange_group` property for supporting separate rearrange groups in the TabControllers. All groups in the container have the same rearrange group, but it can be different from other TabControllers / DockableContainers in your scene.

**Comment by luiq54** [comment]
I have a setup like this. 
![image](https://user-images.githubusercontent.com/51489635/163924177-aa3407a9-693c-4038-a07b-82bef77956ca.png)
![image](https://user-images.githubusercontent.com/51489635/163924213-17b8ca1e-0a29-4326-852c-28bcfc090b15.png)

These containers (color rects ) are part of different containers as you can see in the image. I want to drag a color rect from one container and drop it into another. 
I want to keep a static (non movable + non-dockable window) in the middle unused area. This will be beneficial in creating more dynamic layouts .

**Comment by gilzoide** [comment]
Ok, now I got it, thanks!
I've just tested this kind of layout here and right now DockableContainer doesn't handle nodes coming from other containers.
Shouldn't be hard to pull off, but needs implementation and testing. I also don't know how it would respond to trying to add tabs in an empty container, it's possible we'd have to change how dropping tabs work for this case as well.

**Comment by gilzoide** [comment]
I've implemented this support in a separate branch and opened a PR for it. Feel free to open the branch in Godot and test out the functionality in the new test scene.

**Comment by luiq54** [comment]
I tested it and it works very well !!

**Comment by gilzoide** [comment]
All right, good to hear that ^^
I'll then merge the PR and submit a new version to the Asset Library!
